
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 27 03:15:07 EST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQVQ = 31;
  public static final int CONCAT = 15;
  public static final int EQUALQ = 32;
  public static final int CASE = 22;
  public static final int CAR = 27;
  public static final int INTEGER = 49;
  public static final int CDR = 28;
  public static final int LPAREN = 33;
  public static final int GREATER = 13;
  public static final int HEX = 54;
  public static final int PRINTLN = 24;
  public static final int LESS = 14;
  public static final int RPAREN = 34;
  public static final int LCURL = 38;
  public static final int NOT = 9;
  public static final int AND = 20;
  public static final int OR = 19;
  public static final int COMMA = 36;
  public static final int SEMICOL = 37;
  public static final int CALL = 4;
  public static final int DIV = 45;
  public static final int COMLINE = 48;
  public static final int ASSIGN = 47;
  public static final int LESSEQ = 16;
  public static final int IF = 5;
  public static final int LSQUA = 40;
  public static final int BOOLEAN = 51;
  public static final int EOF = 0;
  public static final int EQUAL = 12;
  public static final int error = 1;
  public static final int BITOR = 11;
  public static final int MUL = 44;
  public static final int ADD = 42;
  public static final int MOD = 46;
  public static final int PAIR = 26;
  public static final int RCURL = 39;
  public static final int COLON = 35;
  public static final int BIN = 53;
  public static final int ELSE = 7;
  public static final int PAIRQ = 30;
  public static final int VARIABLE = 50;
  public static final int BE = 8;
  public static final int LIST = 29;
  public static final int LET = 2;
  public static final int THEN = 6;
  public static final int RSQUA = 41;
  public static final int BITNOT = 21;
  public static final int BITAND = 10;
  public static final int STRING = 52;
  public static final int PROC = 25;
  public static final int GREATEREQ = 17;
  public static final int DEF = 3;
  public static final int SUB = 43;
  public static final int PRINT = 23;
  public static final int NOTEQ = 18;
}

