
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 03 10:52:12 EST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PT = 44;
  public static final int EQVQ = 40;
  public static final int CONCAT = 19;
  public static final int EQUALQ = 41;
  public static final int READINT = 33;
  public static final int PATH = 47;
  public static final int CAR = 35;
  public static final int CASE = 29;
  public static final int INTEGER = 62;
  public static final int DOUBLE = 61;
  public static final int LPAREN = 52;
  public static final int CDR = 36;
  public static final int GREATER = 11;
  public static final int HEX = 66;
  public static final int PRINTLN = 31;
  public static final int LESS = 12;
  public static final int MINUS = 3;
  public static final int RPAREN = 53;
  public static final int SETFG = 50;
  public static final int LCURL = 56;
  public static final int NOT = 18;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int COMMA = 60;
  public static final int LAZY = 23;
  public static final int SEMICOL = 58;
  public static final int CALL = 22;
  public static final int DIV = 5;
  public static final int PLUS = 2;
  public static final int LESSEQ = 13;
  public static final int ASSIGN = 20;
  public static final int IF = 26;
  public static final int BOOLEAN = 64;
  public static final int EOF = 0;
  public static final int EQUAL = 10;
  public static final int SIZE = 39;
  public static final int error = 1;
  public static final int BITOR = 8;
  public static final int MUL = 4;
  public static final int MOD = 6;
  public static final int SETBG = 51;
  public static final int PAIR = 34;
  public static final int RCURL = 57;
  public static final int COLON = 59;
  public static final int BIN = 65;
  public static final int LBRACE = 55;
  public static final int ELSE = 28;
  public static final int PAIRQ = 37;
  public static final int VARIABLE = 63;
  public static final int CANVAS = 43;
  public static final int READ = 32;
  public static final int LIST = 38;
  public static final int SUBSTR = 42;
  public static final int CLEAR = 49;
  public static final int LET = 24;
  public static final int RBRACE = 54;
  public static final int CPATH = 48;
  public static final int THEN = 27;
  public static final int BITNOT = 9;
  public static final int BITAND = 7;
  public static final int STRING = 67;
  public static final int PROC = 21;
  public static final int GREATEREQ = 14;
  public static final int DEF = 25;
  public static final int RECT = 45;
  public static final int CIRCLE = 46;
  public static final int PRINT = 30;
  public static final int NOTEQ = 15;
}

